version: '3.5'

services:
  e-learning-api:
    depends_on:
      - e-learning-db
    #      - e-learning-queue
    build:
      context: '.'
      dockerfile: 'Dockerfile.dev'
    container_name: e-learning-api
    restart: always
    environment:
      #      - QUEUE_CONNECTION=redis
      #      - REDIS_HOST=e-learning-queue
      #      - REDIS_PORT=6379
      - DB_HOST=e-learning-db
      - DB_PORT=3306
      - DB_DATABASE=e-learning
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./:/var/www
    ports:
      - 9500:80
  e-learning-db:
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./dockerdb.sql:/data/application/init.sql
      - ./.dbdata:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  e-learning-phpmyadmin:
    depends_on:
      - e-learning-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9506:80'
    environment:
      PMA_HOST: e-learning-db
      MYSQL_ROOT_PASSWORD: secret
#  e-learning-queue:
#    image: redis
#    restart: always
